model:
  Embedding_ChemBERT: 384
  hidden_dim: 256
  nodes: 96
  embedding_dim: 384      # set this same as Embedding_ChemBERT
  num_layers: 3

training:
  max_epochs: 200
  patience: 10
  early_stop_epochs: 30
  batch_size: 512
  lr: 0.001
  lr_decay_factor: 0.1
  weight_decay: 0.01
  l1_beta: 0.25
